### ISSUE TITLE
Nomenclature/Definition of Top Level Domain

### ISSUE THREAD

**Issue by chrisport** [bobesa/go-domain-util#3]
The nomenclature is a bit confusing. 
The **top level domain** of a url, for example  **www.example.com** is **com**, not **example.com**. See also [IANA](https://www.iana.org/domains/root) or [Wikipedia](https://en.wikipedia.org/wiki/Top-level_domain)
My name suggestion would be:
```
www.example.co.uk

Domain name: example.co.uk
Subdomain: www
Domain Suffix: co.uk
TLD: uk
```

PS: I know it seems picky, but it costed me some time now to figure out what the methods are actually doing.

**Comment by gildor478** [comment]
.co.uk is a SLD (second level domain) not a TLD. Eventhough people may consider it as a TLD, because you probably cannot easily register "foobar.uk".

With www.example.co.uk, you have all the possible combination:
Subdomain: www
Domain: example.co.uk

Subdomain: www.example
Domain: co.uk (which happens to be a SLD)

Subdomain: www.example.co
Domain: uk (which happens to be a TLD)
